export const ROUTES = {
	root: '/',
	login: 'login',
	forgotPassword: 'forgot-password',
	resetPassword: 'reset-password',
	register: 'register',
	dashboard: '/dashboard',
	profile: '/profile',
	careerPaths: '/career-paths',
	education: '/education',
	experience: '/experience',
	projects: '/projects',
	skills: '/skills',
	statistics: '/statistics',
};
